### ISSUE TITLE
make command does not work when trying to compile Pepper.js on MS Windows

### ISSUE THREAD

**Issue by briangavin** [google/pepper.js#8]
If you try to make the Pepper.js files on MS Windows you get a build error when trying to compile the release version of emscripten.  The debug version seems to work properly.

make TOOLCHAIN=emscripten CONFIG=Release

It appears to be a problem with copying finished .js file uses 'cp' should be 'copy'?

**Comment by joshpeterson** [comment]
I'm not quite sure about the cause of this issue, but I think that you can work around it my changing command line for the `make` command from

```
make TOOLCHAIN=emscripten CONFIG=Release
```

to

```
make TOOLCHAIN=emscripten CONFIG=release
```

Note that the `CONFIG` value is `release` not `Release`. On my Windows 7 machine I was getting the following error with the former command line, but the latter command line seems to work:

```
undefined:1

^
SyntaxError: Unexpected token ILLEGAL
    at eval (native)
    at globalEval (C:\Program Files\Emscripten\emscripten\1.12.0\src\compiler.js:105:8)
    at load (C:\Program Files\Emscripten\emscripten\1.12.0\src\compiler.js:61:5)
    at Object.<anonymous> (C:\Program Files\Emscripten\emscripten\1.12.0\src\compiler.js:225:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\1.12.0\emscripten.py", line 1405, in <module>
    _main(environ=os.environ)
  File "C:\Program Files\Emscripten\emscripten\1.12.0\emscripten.py", line 1393, in _main
    temp_files.run_and_clean(lambda: main(
  File "C:\Program Files\Emscripten\emscripten\1.12.0\tools\tempfiles.py", line 39, in run_and_clean
    return func()
  File "C:\Program Files\Emscripten\emscripten\1.12.0\emscripten.py", line 1401, in <lambda>
    DEBUG_CACHE=DEBUG_CACHE,
  File "C:\Program Files\Emscripten\emscripten\1.12.0\emscripten.py", line 1288, in main
    jcache=jcache, temp_files=temp_files, DEBUG=DEBUG, DEBUG_CACHE=DEBUG_CACHE)
  File "C:\Program Files\Emscripten\emscripten\1.12.0\emscripten.py", line 292, in emscript
    assert len(output) == 2, 'Did not receive forwarded data in an output - process failed? We only got: ' + output[0][-3000:]
AssertionError: Did not receive forwarded data in an output - process failed? We only got:
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\1.12.0\emcc", line 1525, in <module>
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "C:\Program Files\Emscripten\emscripten\1.12.0\tools\shared.py", line 1276, in emscripten
    assert os.path.exists(filename + '.o.js') and len(open(filename + '.o.js', 'r').read()) > 0, 'Emscripten failed to generate .js: ' + str(compiler_output)
AssertionError: Emscripten failed to generate .js:
make[1]: *** [emscripten/Release/hello_world_unstripped.js] Error 1
make[1]: Leaving directory `C:/Users/Josh/Documents/development/pepper.js/examples/hello_world'
make: *** [hello_world_TARGET] Error 2
```

**Comment by briangavin** [comment]
The bug is still there even with 'release' instead of Release.  cp command is being used for copy should be copy on Windows. 

Note -
make TOOLCHAIN=emscripten CONFIG=Debug  works correctly.

error -
make: **\* [ppapi_cpp_TARGET ] Error 2

**Comment by joshpeterson** [comment]
Ok, sorry. I must have been facing a different problem then.
